### ISSUE TITLE
Code coverage is inaccurate as code in _internal_test files is counted towards total code

### ISSUE THREAD

**Issue by elessar-ch** [bespinian/livelint#42]

**Comment by cldmstr** [comment]
I tested this out and the test reporting is correct. It makes no difference if you remove the `*_internal_*` in the test file names or not.

**Comment by cldmstr** [comment]
Checked again by moving all the tests in the `_internal_test` files to the `livelint_test` package and this does actually make a difference in coverage and brings the total line coverage up to 31%.
